/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Class.Job;
import General.Tools;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author just_
 */
public class formScreen extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public formScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        tableJob.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelCargos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMenorSalario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMaiorSalario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnInserir = new javax.swing.JButton();
        btnTabela = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJob = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        labelQuantidade = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto HR");
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 576));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                TableUpdate(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel1.setText("Código Identificador");

        jLabel2.setText("Nome do Cargo");

        jLabel3.setText("Menor Salário");

        jLabel4.setText("Maior Salário");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "Comandos"));

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/insert-file.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spreadsheet-cell-row.png"))); // NOI18N
        btnTabela.setText("Tabela");
        btnTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabelaActionPerformed(evt);
            }
        });

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rubbish-bin.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shuffle.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recycle.png"))); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loupe.png"))); // NOI18N
        jButton1.setText("Inspecionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnTabela)
                    .addComponent(btnDeletar)
                    .addComponent(btnAlterar)
                    .addComponent(btnLimpar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resultado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        tableJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JOB_ID", "JOB_TITLE", "MIN_SALARY", "MAX_SALARY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableJob.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableJob);
        if (tableJob.getColumnModel().getColumnCount() > 0) {
            tableJob.getColumnModel().getColumn(0).setResizable(false);
            tableJob.getColumnModel().getColumn(1).setResizable(false);
            tableJob.getColumnModel().getColumn(2).setResizable(false);
            tableJob.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel5.setText("Quantidade de linhas:");

        labelQuantidade.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout panelCargosLayout = new javax.swing.GroupLayout(panelCargos);
        panelCargos.setLayout(panelCargosLayout);
        panelCargosLayout.setHorizontalGroup(
            panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelCargosLayout.createSequentialGroup()
                        .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCargosLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelQuantidade))
                            .addGroup(panelCargosLayout.createSequentialGroup()
                                .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMenorSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMaiorSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelCargosLayout.setVerticalGroup(
            panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCargosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCargosLayout.createSequentialGroup()
                        .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMenorSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaiorSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelCargosLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCargosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelQuantidade))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gerenciador de Cargos", panelCargos);

        jMenu1.setText("Arquivo");

        menuExit.setText("Sair");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void btnTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabelaActionPerformed
        // TODO add your handling code here:
        refreshJobTable();
    }//GEN-LAST:event_btnTabelaActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // TODO add your handling code here:
        String cargo = txtCargo.getText();
        String codigo = txtCodigo.getText();
        String menorSalario = txtMenorSalario.getText();
        String maiorSalario = txtMaiorSalario.getText();

        if (!cargo.isEmpty()
                && !codigo.isEmpty()
                && !menorSalario.isEmpty()
                && !maiorSalario.isEmpty()) {
            // Se nada estiver vazio

            // Ler Salario
            BigDecimal salarioMin = Tools.parseMoney(menorSalario);
            BigDecimal salarioMax = Tools.parseMoney(maiorSalario);

            if (salarioMin.intValue() == -1 || salarioMax.intValue() == -1) {
                Tools.error("Valores dos salários inválidos.");
            } else {
                Job job = new Job(codigo, cargo, salarioMin, salarioMax);

                if (job.insertIntoDatabase()) {
                    Tools.alert("Inserido com sucesso.");
                    refreshJobTable();
                } else {
                    Tools.error("Erro ao inserir no banco de dados.");
                }
            }
        } else {
            Tools.alert("Preencha todos os valores.");
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // TODO add your handling code here:

        Job job = selectJob();

        if (!job.getId().isEmpty()) {
            
            formJobViwer jobViwer = loadJobViwer(job);

            boolean confirm = Tools.confirm("Deseja mesmo deletar?");

            if (confirm) {
                jobViwer.dispose();
                boolean success = job.deleteFromDatabase();

                if (success) {
                    Tools.alert("Deletado com sucesso.");
                    refreshJobTable();
                    clearInput();
                } else {
                    Tools.error("Erro ao deletar.");
                }
            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        clearInput();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:

        Job job = selectJob();

        if (!job.getId().isEmpty()) {
            formJobViwer jobViwer = loadJobViwer(job);
            
            jobViwer.setEditable();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void TableUpdate(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_TableUpdate
        // TODO add your handling code here:
        refreshJobTable();
    }//GEN-LAST:event_TableUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Job job = selectJob();

        if (!job.getId().isEmpty()) {
            formJobViwer jobViwer = loadJobViwer(job);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /* Funções */
    private void clearInput() {
        txtCargo.setText(null);
        txtCodigo.setText(null);
        txtMaiorSalario.setText(null);
        txtMenorSalario.setText(null);
    }

    private Job selectJob() {
        DefaultTableModel table = (DefaultTableModel) tableJob.getModel();
        Job job = new Job();

        int row = tableJob.getSelectedRow();

        if (row == -1) {
            Tools.error("Selecione uma entrada válida na tabela.");
        } else {

            String codigo = (String) table.getValueAt(row, 0);
            String cargo = (String) table.getValueAt(row, 1);
            String menorSalario = (String) table.getValueAt(row, 2);
            String maiorSalario = (String) table.getValueAt(row, 3);

            menorSalario = Tools.parseNumber(menorSalario);
            maiorSalario = Tools.parseNumber(maiorSalario);

            BigDecimal salarioMin = Tools.parseMoney(menorSalario);
            BigDecimal salarioMax = Tools.parseMoney(maiorSalario);

            job = new Job(codigo, cargo, salarioMin, salarioMax);
        }

        return job;
    }

    private formJobViwer loadJobViwer(Job job) {
        formJobViwer.currentJob = job;

        formJobViwer jobViwer = new formJobViwer();
        jobViwer.setLocationRelativeTo(btnDeletar);
        jobViwer.setVisible(true);
        
        return jobViwer;
    }

    public void refreshJobTable() {
        ArrayList<Job> jobs = new ArrayList<>();
        jobs = Job.selectAllFromDatabase();

        DefaultTableModel table = (DefaultTableModel) tableJob.getModel();

        table.setRowCount(0);

        jobs.forEach((job) -> {
            table.addRow(new Object[]{
                job.getId(),
                job.getTitle(),
                Tools.moneyFormat(job.getMinSalary()),
                Tools.moneyFormat(job.getMaxSalary())});
        });

        int rowAmount = table.getRowCount();
        labelQuantidade.setText(String.valueOf(rowAmount));
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnTabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JPanel panelCargos;
    private javax.swing.JTable tableJob;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtMaiorSalario;
    private javax.swing.JTextField txtMenorSalario;
    // End of variables declaration//GEN-END:variables
}
